// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: api_client.sql

package db

import (
	"context"
)

const getAPIClientByKeyHash = `-- name: GetAPIClientByKeyHash :one
SELECT id, name, api_key_hash, is_active, created_at, updated_at
FROM api_clients
WHERE api_key_hash = $1 AND is_active = true
`

func (q *Queries) GetAPIClientByKeyHash(ctx context.Context, apiKeyHash string) (ApiClient, error) {
	row := q.db.QueryRowContext(ctx, getAPIClientByKeyHash, apiKeyHash)
	var i ApiClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKeyHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAPIClient = `-- name: InsertAPIClient :one
INSERT INTO api_clients (name, api_key_hash)
VALUES ($1, $2)
RETURNING id, name, api_key_hash, is_active, created_at, updated_at
`

type InsertAPIClientParams struct {
	Name       string `json:"name"`
	ApiKeyHash string `json:"api_key_hash"`
}

func (q *Queries) InsertAPIClient(ctx context.Context, arg InsertAPIClientParams) (ApiClient, error) {
	row := q.db.QueryRowContext(ctx, insertAPIClient, arg.Name, arg.ApiKeyHash)
	var i ApiClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKeyHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
