// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dead_letter.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const countDeadLettersByChannel = `-- name: CountDeadLettersByChannel :many
SELECT channel, COUNT(*) AS count
FROM dead_letter_messages
WHERE tenant_id = $1 AND replayed_at IS NULL
GROUP BY channel
`

type CountDeadLettersByChannelRow struct {
	Channel string `json:"channel"`
	Count   int64  `json:"count"`
}

func (q *Queries) CountDeadLettersByChannel(ctx context.Context, tenantID uuid.UUID) ([]CountDeadLettersByChannelRow, error) {
	rows, err := q.db.QueryContext(ctx, countDeadLettersByChannel, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountDeadLettersByChannelRow{}
	for rows.Next() {
		var i CountDeadLettersByChannelRow
		if err := rows.Scan(&i.Channel, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createDeadLetter = `-- name: CreateDeadLetter :one
INSERT INTO dead_letter_messages (
    tenant_id,
    notification_id,
    channel,
    original_topic,
    payload,
    failure_reason,
    error_message,
    attempts
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, tenant_id, notification_id, channel, original_topic, payload, failure_reason, error_message, attempts, replayed_at, created_at
`

type CreateDeadLetterParams struct {
	TenantID       uuid.UUID       `json:"tenant_id"`
	NotificationID uuid.UUID       `json:"notification_id"`
	Channel        string          `json:"channel"`
	OriginalTopic  string          `json:"original_topic"`
	Payload        json.RawMessage `json:"payload"`
	FailureReason  string          `json:"failure_reason"`
	ErrorMessage   string          `json:"error_message"`
	Attempts       int32           `json:"attempts"`
}

func (q *Queries) CreateDeadLetter(ctx context.Context, arg CreateDeadLetterParams) (DeadLetterMessage, error) {
	row := q.db.QueryRowContext(ctx, createDeadLetter,
		arg.TenantID,
		arg.NotificationID,
		arg.Channel,
		arg.OriginalTopic,
		arg.Payload,
		arg.FailureReason,
		arg.ErrorMessage,
		arg.Attempts,
	)
	var i DeadLetterMessage
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.NotificationID,
		&i.Channel,
		&i.OriginalTopic,
		&i.Payload,
		&i.FailureReason,
		&i.ErrorMessage,
		&i.Attempts,
		&i.ReplayedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDeadLetter = `-- name: DeleteDeadLetter :exec
DELETE FROM dead_letter_messages
WHERE id = $1 AND tenant_id = $2
`

type DeleteDeadLetterParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteDeadLetter(ctx context.Context, arg DeleteDeadLetterParams) error {
	_, err := q.db.ExecContext(ctx, deleteDeadLetter, arg.ID, arg.TenantID)
	return err
}

const getDeadLetterByID = `-- name: GetDeadLetterByID :one
SELECT id, tenant_id, notification_id, channel, original_topic, payload, failure_reason, error_message, attempts, replayed_at, created_at FROM dead_letter_messages
WHERE id = $1 AND tenant_id = $2
`

type GetDeadLetterByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetDeadLetterByID(ctx context.Context, arg GetDeadLetterByIDParams) (DeadLetterMessage, error) {
	row := q.db.QueryRowContext(ctx, getDeadLetterByID, arg.ID, arg.TenantID)
	var i DeadLetterMessage
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.NotificationID,
		&i.Channel,
		&i.OriginalTopic,
		&i.Payload,
		&i.FailureReason,
		&i.ErrorMessage,
		&i.Attempts,
		&i.ReplayedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listDeadLetters = `-- name: ListDeadLetters :many
SELECT id, tenant_id, notification_id, channel, original_topic, payload, failure_reason, error_message, attempts, replayed_at, created_at FROM dead_letter_messages
WHERE tenant_id = $1::uuid
  AND COALESCE(NULLIF($2::text, ''), channel) = channel
  AND (NOT $3::boolean OR replayed_at IS NULL)
ORDER BY created_at DESC
LIMIT $5::int
OFFSET $4::int
`

type ListDeadLettersParams struct {
	TenantID       uuid.UUID `json:"tenant_id"`
	Channel        string    `json:"channel"`
	UnreplayedOnly bool      `json:"unreplayed_only"`
	Offset         int32     `json:"offset_"`
	Limit          int32     `json:"limit_"`
}

func (q *Queries) ListDeadLetters(ctx context.Context, arg ListDeadLettersParams) ([]DeadLetterMessage, error) {
	rows, err := q.db.QueryContext(ctx, listDeadLetters,
		arg.TenantID,
		arg.Channel,
		arg.UnreplayedOnly,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeadLetterMessage{}
	for rows.Next() {
		var i DeadLetterMessage
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.NotificationID,
			&i.Channel,
			&i.OriginalTopic,
			&i.Payload,
			&i.FailureReason,
			&i.ErrorMessage,
			&i.Attempts,
			&i.ReplayedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeadLetterReplayed = `-- name: MarkDeadLetterReplayed :exec
UPDATE dead_letter_messages
SET replayed_at = now()
WHERE id = $1 AND tenant_id = $2
`

type MarkDeadLetterReplayedParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) MarkDeadLetterReplayed(ctx context.Context, arg MarkDeadLetterReplayedParams) error {
	_, err := q.db.ExecContext(ctx, markDeadLetterReplayed, arg.ID, arg.TenantID)
	return err
}
