// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: delivery.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getLatestDeliveryLog = `-- name: GetLatestDeliveryLog :one
SELECT id, notification_id, channel, provider, status, provider_message_id, error_message, error_code, retry_count, attempted_at, delivered_at FROM delivery_logs
WHERE notification_id = $1
ORDER BY attempted_at DESC
LIMIT 1
`

func (q *Queries) GetLatestDeliveryLog(ctx context.Context, notificationID uuid.UUID) (DeliveryLog, error) {
	row := q.db.QueryRowContext(ctx, getLatestDeliveryLog, notificationID)
	var i DeliveryLog
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.Channel,
		&i.Provider,
		&i.Status,
		&i.ProviderMessageID,
		&i.ErrorMessage,
		&i.ErrorCode,
		&i.RetryCount,
		&i.AttemptedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const insertDeliveryLog = `-- name: InsertDeliveryLog :one
INSERT INTO delivery_logs (
    notification_id,
    channel,
    provider,
    status,
    provider_message_id,
    error_message,
    error_code,
    retry_count,
    delivered_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, notification_id, channel, provider, status, provider_message_id, error_message, error_code, retry_count, attempted_at, delivered_at
`

type InsertDeliveryLogParams struct {
	NotificationID    uuid.UUID      `json:"notification_id"`
	Channel           string         `json:"channel"`
	Provider          string         `json:"provider"`
	Status            string         `json:"status"`
	ProviderMessageID sql.NullString `json:"provider_message_id"`
	ErrorMessage      sql.NullString `json:"error_message"`
	ErrorCode         sql.NullString `json:"error_code"`
	RetryCount        int32          `json:"retry_count"`
	DeliveredAt       sql.NullTime   `json:"delivered_at"`
}

func (q *Queries) InsertDeliveryLog(ctx context.Context, arg InsertDeliveryLogParams) (DeliveryLog, error) {
	row := q.db.QueryRowContext(ctx, insertDeliveryLog,
		arg.NotificationID,
		arg.Channel,
		arg.Provider,
		arg.Status,
		arg.ProviderMessageID,
		arg.ErrorMessage,
		arg.ErrorCode,
		arg.RetryCount,
		arg.DeliveredAt,
	)
	var i DeliveryLog
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.Channel,
		&i.Provider,
		&i.Status,
		&i.ProviderMessageID,
		&i.ErrorMessage,
		&i.ErrorCode,
		&i.RetryCount,
		&i.AttemptedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const listDeliveryLogsByNotification = `-- name: ListDeliveryLogsByNotification :many
SELECT id, notification_id, channel, provider, status, provider_message_id, error_message, error_code, retry_count, attempted_at, delivered_at FROM delivery_logs
WHERE notification_id = $1
ORDER BY attempted_at ASC
`

func (q *Queries) ListDeliveryLogsByNotification(ctx context.Context, notificationID uuid.UUID) ([]DeliveryLog, error) {
	rows, err := q.db.QueryContext(ctx, listDeliveryLogsByNotification, notificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliveryLog{}
	for rows.Next() {
		var i DeliveryLog
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.Channel,
			&i.Provider,
			&i.Status,
			&i.ProviderMessageID,
			&i.ErrorMessage,
			&i.ErrorCode,
			&i.RetryCount,
			&i.AttemptedAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
