// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: device_token.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deactivateDeviceToken = `-- name: DeactivateDeviceToken :exec
UPDATE device_tokens
SET is_active = false, updated_at = NOW()
WHERE tenant_id = $1 AND token = $2
`

type DeactivateDeviceTokenParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Token    string    `json:"token"`
}

func (q *Queries) DeactivateDeviceToken(ctx context.Context, arg DeactivateDeviceTokenParams) error {
	_, err := q.db.ExecContext(ctx, deactivateDeviceToken, arg.TenantID, arg.Token)
	return err
}

const getDeviceToken = `-- name: GetDeviceToken :one
SELECT id, tenant_id, user_id, token, platform, is_active, created_at, updated_at FROM device_tokens
WHERE tenant_id = $1 AND token = $2
`

type GetDeviceTokenParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Token    string    `json:"token"`
}

func (q *Queries) GetDeviceToken(ctx context.Context, arg GetDeviceTokenParams) (DeviceToken, error) {
	row := q.db.QueryRowContext(ctx, getDeviceToken, arg.TenantID, arg.Token)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Token,
		&i.Platform,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveDeviceTokensByUser = `-- name: ListActiveDeviceTokensByUser :many
SELECT id, tenant_id, user_id, token, platform, is_active, created_at, updated_at FROM device_tokens
WHERE tenant_id = $1 AND user_id = $2 AND is_active = true
ORDER BY created_at DESC
`

type ListActiveDeviceTokensByUserParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   string    `json:"user_id"`
}

func (q *Queries) ListActiveDeviceTokensByUser(ctx context.Context, arg ListActiveDeviceTokensByUserParams) ([]DeviceToken, error) {
	rows, err := q.db.QueryContext(ctx, listActiveDeviceTokensByUser, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceToken{}
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Token,
			&i.Platform,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :one
INSERT INTO device_tokens (tenant_id, user_id, token, platform)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, token) DO UPDATE
    SET user_id    = EXCLUDED.user_id,
        platform   = EXCLUDED.platform,
        is_active  = true,
        updated_at = NOW()
RETURNING id, tenant_id, user_id, token, platform, is_active, created_at, updated_at
`

type UpsertDeviceTokenParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   string    `json:"user_id"`
	Token    string    `json:"token"`
	Platform string    `json:"platform"`
}

func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (DeviceToken, error) {
	row := q.db.QueryRowContext(ctx, upsertDeviceToken,
		arg.TenantID,
		arg.UserID,
		arg.Token,
		arg.Platform,
	)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Token,
		&i.Platform,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
