// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: inapp.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const countUnread = `-- name: CountUnread :one
SELECT COUNT(*) FROM inapp_messages
WHERE tenant_id = $1
  AND recipient_id = $2
  AND read_at IS NULL
`

type CountUnreadParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	RecipientID string    `json:"recipient_id"`
}

func (q *Queries) CountUnread(ctx context.Context, arg CountUnreadParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnread, arg.TenantID, arg.RecipientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getInAppMessage = `-- name: GetInAppMessage :one
SELECT id, tenant_id, notification_id, recipient_id, title, body, payload, read_at, created_at FROM inapp_messages
WHERE id = $1 AND tenant_id = $2
`

type GetInAppMessageParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetInAppMessage(ctx context.Context, arg GetInAppMessageParams) (InappMessage, error) {
	row := q.db.QueryRowContext(ctx, getInAppMessage, arg.ID, arg.TenantID)
	var i InappMessage
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.NotificationID,
		&i.RecipientID,
		&i.Title,
		&i.Body,
		&i.Payload,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertInAppMessage = `-- name: InsertInAppMessage :one
INSERT INTO inapp_messages (
    tenant_id,
    notification_id,
    recipient_id,
    title,
    body,
    payload
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, tenant_id, notification_id, recipient_id, title, body, payload, read_at, created_at
`

type InsertInAppMessageParams struct {
	TenantID       uuid.UUID       `json:"tenant_id"`
	NotificationID uuid.NullUUID   `json:"notification_id"`
	RecipientID    string          `json:"recipient_id"`
	Title          string          `json:"title"`
	Body           string          `json:"body"`
	Payload        json.RawMessage `json:"payload"`
}

func (q *Queries) InsertInAppMessage(ctx context.Context, arg InsertInAppMessageParams) (InappMessage, error) {
	row := q.db.QueryRowContext(ctx, insertInAppMessage,
		arg.TenantID,
		arg.NotificationID,
		arg.RecipientID,
		arg.Title,
		arg.Body,
		arg.Payload,
	)
	var i InappMessage
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.NotificationID,
		&i.RecipientID,
		&i.Title,
		&i.Body,
		&i.Payload,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listInbox = `-- name: ListInbox :many
SELECT id, tenant_id, notification_id, recipient_id, title, body, payload, read_at, created_at FROM inapp_messages
WHERE tenant_id = $1::uuid
  AND recipient_id = $2::text
  AND (NOT $3::boolean OR read_at IS NULL)
ORDER BY created_at DESC
LIMIT $5::int
OFFSET $4::int
`

type ListInboxParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	RecipientID string    `json:"recipient_id"`
	UnreadOnly  bool      `json:"unread_only"`
	Offset      int32     `json:"offset_"`
	Limit       int32     `json:"limit_"`
}

func (q *Queries) ListInbox(ctx context.Context, arg ListInboxParams) ([]InappMessage, error) {
	rows, err := q.db.QueryContext(ctx, listInbox,
		arg.TenantID,
		arg.RecipientID,
		arg.UnreadOnly,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InappMessage{}
	for rows.Next() {
		var i InappMessage
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.NotificationID,
			&i.RecipientID,
			&i.Title,
			&i.Body,
			&i.Payload,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllInAppMessagesRead = `-- name: MarkAllInAppMessagesRead :exec
UPDATE inapp_messages
SET read_at = now()
WHERE tenant_id = $1 AND recipient_id = $2 AND read_at IS NULL
`

type MarkAllInAppMessagesReadParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	RecipientID string    `json:"recipient_id"`
}

func (q *Queries) MarkAllInAppMessagesRead(ctx context.Context, arg MarkAllInAppMessagesReadParams) error {
	_, err := q.db.ExecContext(ctx, markAllInAppMessagesRead, arg.TenantID, arg.RecipientID)
	return err
}

const markInAppMessageRead = `-- name: MarkInAppMessageRead :exec
UPDATE inapp_messages
SET read_at = now()
WHERE id = $1 AND tenant_id = $2 AND recipient_id = $3 AND read_at IS NULL
`

type MarkInAppMessageReadParams struct {
	ID          uuid.UUID `json:"id"`
	TenantID    uuid.UUID `json:"tenant_id"`
	RecipientID string    `json:"recipient_id"`
}

func (q *Queries) MarkInAppMessageRead(ctx context.Context, arg MarkInAppMessageReadParams) error {
	_, err := q.db.ExecContext(ctx, markInAppMessageRead, arg.ID, arg.TenantID, arg.RecipientID)
	return err
}
