// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ApiClient struct {
	ID         uuid.UUID     `json:"id"`
	Name       string        `json:"name"`
	ApiKeyHash string        `json:"api_key_hash"`
	IsActive   bool          `json:"is_active"`
	CreatedAt  time.Time     `json:"created_at"`
	UpdatedAt  time.Time     `json:"updated_at"`
	TenantID   uuid.NullUUID `json:"tenant_id"`
}

type DeadLetterMessage struct {
	ID             uuid.UUID       `json:"id"`
	TenantID       uuid.UUID       `json:"tenant_id"`
	NotificationID uuid.UUID       `json:"notification_id"`
	Channel        string          `json:"channel"`
	OriginalTopic  string          `json:"original_topic"`
	Payload        json.RawMessage `json:"payload"`
	FailureReason  string          `json:"failure_reason"`
	ErrorMessage   string          `json:"error_message"`
	Attempts       int32           `json:"attempts"`
	ReplayedAt     sql.NullTime    `json:"replayed_at"`
	CreatedAt      time.Time       `json:"created_at"`
}

type DeliveryLog struct {
	ID                uuid.UUID      `json:"id"`
	NotificationID    uuid.UUID      `json:"notification_id"`
	Channel           string         `json:"channel"`
	Provider          string         `json:"provider"`
	Status            string         `json:"status"`
	ProviderMessageID sql.NullString `json:"provider_message_id"`
	ErrorMessage      sql.NullString `json:"error_message"`
	ErrorCode         sql.NullString `json:"error_code"`
	RetryCount        int32          `json:"retry_count"`
	AttemptedAt       time.Time      `json:"attempted_at"`
	DeliveredAt       sql.NullTime   `json:"delivered_at"`
}

type Notification struct {
	ID               uuid.UUID       `json:"id"`
	IdempotencyKey   sql.NullString  `json:"idempotency_key"`
	Type             string          `json:"type"`
	Channel          string          `json:"channel"`
	RecipientID      string          `json:"recipient_id"`
	RecipientAddress sql.NullString  `json:"recipient_address"`
	TemplateID       uuid.NullUUID   `json:"template_id"`
	Payload          json.RawMessage `json:"payload"`
	Priority         int32           `json:"priority"`
	Status           string          `json:"status"`
	ScheduledAt      sql.NullTime    `json:"scheduled_at"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
	TenantID         uuid.NullUUID   `json:"tenant_id"`
}

type Preference struct {
	ID                     uuid.UUID      `json:"id"`
	UserID                 string         `json:"user_id"`
	Channel                string         `json:"channel"`
	Enabled                bool           `json:"enabled"`
	QuietHoursStart        sql.NullTime   `json:"quiet_hours_start"`
	QuietHoursEnd          sql.NullTime   `json:"quiet_hours_end"`
	FrequencyCap           sql.NullInt32  `json:"frequency_cap"`
	FrequencyWindowMinutes sql.NullInt32  `json:"frequency_window_minutes"`
	Timezone               sql.NullString `json:"timezone"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              time.Time      `json:"updated_at"`
	TenantID               uuid.NullUUID  `json:"tenant_id"`
}

type Template struct {
	ID              uuid.UUID             `json:"id"`
	Name            string                `json:"name"`
	Channel         string                `json:"channel"`
	SubjectTemplate sql.NullString        `json:"subject_template"`
	BodyTemplate    string                `json:"body_template"`
	Metadata        pqtype.NullRawMessage `json:"metadata"`
	Version         int32                 `json:"version"`
	IsActive        bool                  `json:"is_active"`
	CreatedAt       time.Time             `json:"created_at"`
	UpdatedAt       time.Time             `json:"updated_at"`
	TenantID        uuid.NullUUID         `json:"tenant_id"`
}

type Tenant struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
