// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: notification.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const cancelNotification = `-- name: CancelNotification :one
UPDATE notifications
SET status = 'dropped', updated_at = NOW()
WHERE id = $1 AND status IN ('pending', 'queued')
RETURNING id, idempotency_key, type, channel, recipient_id, recipient_address, template_id, payload, priority, status, scheduled_at, created_at, updated_at
`

func (q *Queries) CancelNotification(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRowContext(ctx, cancelNotification, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Type,
		&i.Channel,
		&i.RecipientID,
		&i.RecipientAddress,
		&i.TemplateID,
		&i.Payload,
		&i.Priority,
		&i.Status,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countNotifications = `-- name: CountNotifications :one
SELECT COUNT(*) FROM notifications
WHERE
    ($1::text = '' OR recipient_id = $1) AND
    ($2::text = '' OR channel = $2) AND
    ($3::text = '' OR status = $3)
`

type CountNotificationsParams struct {
	RecipientID string `json:"recipient_id"`
	Channel     string `json:"channel"`
	Status      string `json:"status"`
}

func (q *Queries) CountNotifications(ctx context.Context, arg CountNotificationsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNotifications, arg.RecipientID, arg.Channel, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, idempotency_key, type, channel, recipient_id, recipient_address, template_id, payload, priority, status, scheduled_at, created_at, updated_at FROM notifications
WHERE id = $1
`

func (q *Queries) GetNotificationByID(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRowContext(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Type,
		&i.Channel,
		&i.RecipientID,
		&i.RecipientAddress,
		&i.TemplateID,
		&i.Payload,
		&i.Priority,
		&i.Status,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationByIdempotencyKey = `-- name: GetNotificationByIdempotencyKey :one
SELECT id, idempotency_key, type, channel, recipient_id, recipient_address, template_id, payload, priority, status, scheduled_at, created_at, updated_at FROM notifications
WHERE idempotency_key = $1
`

func (q *Queries) GetNotificationByIdempotencyKey(ctx context.Context, idempotencyKey sql.NullString) (Notification, error) {
	row := q.db.QueryRowContext(ctx, getNotificationByIdempotencyKey, idempotencyKey)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Type,
		&i.Channel,
		&i.RecipientID,
		&i.RecipientAddress,
		&i.TemplateID,
		&i.Payload,
		&i.Priority,
		&i.Status,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notifications (
    idempotency_key,
    type,
    channel,
    recipient_id,
    recipient_address,
    template_id,
    payload,
    priority,
    status,
    scheduled_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, idempotency_key, type, channel, recipient_id, recipient_address, template_id, payload, priority, status, scheduled_at, created_at, updated_at
`

type InsertNotificationParams struct {
	IdempotencyKey   sql.NullString  `json:"idempotency_key"`
	Type             string          `json:"type"`
	Channel          string          `json:"channel"`
	RecipientID      string          `json:"recipient_id"`
	RecipientAddress sql.NullString  `json:"recipient_address"`
	TemplateID       uuid.NullUUID   `json:"template_id"`
	Payload          json.RawMessage `json:"payload"`
	Priority         int32           `json:"priority"`
	Status           string          `json:"status"`
	ScheduledAt      sql.NullTime    `json:"scheduled_at"`
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, insertNotification,
		arg.IdempotencyKey,
		arg.Type,
		arg.Channel,
		arg.RecipientID,
		arg.RecipientAddress,
		arg.TemplateID,
		arg.Payload,
		arg.Priority,
		arg.Status,
		arg.ScheduledAt,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Type,
		&i.Channel,
		&i.RecipientID,
		&i.RecipientAddress,
		&i.TemplateID,
		&i.Payload,
		&i.Priority,
		&i.Status,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueScheduledNotifications = `-- name: ListDueScheduledNotifications :many
SELECT id, idempotency_key, type, channel, recipient_id, recipient_address, template_id, payload, priority, status, scheduled_at, created_at, updated_at FROM notifications
WHERE status = 'pending'
  AND scheduled_at IS NOT NULL
  AND scheduled_at <= NOW()
ORDER BY priority ASC, scheduled_at ASC
LIMIT $1
`

func (q *Queries) ListDueScheduledNotifications(ctx context.Context, limit int32) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listDueScheduledNotifications, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.IdempotencyKey,
			&i.Type,
			&i.Channel,
			&i.RecipientID,
			&i.RecipientAddress,
			&i.TemplateID,
			&i.Payload,
			&i.Priority,
			&i.Status,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, idempotency_key, type, channel, recipient_id, recipient_address, template_id, payload, priority, status, scheduled_at, created_at, updated_at FROM notifications
WHERE
    ($1::text = '' OR recipient_id = $1) AND
    ($2::text = '' OR channel = $2) AND
    ($3::text = '' OR status = $3)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListNotificationsParams struct {
	RecipientID string `json:"recipient_id"`
	Channel     string `json:"channel"`
	Status      string `json:"status"`
	Offset      int32  `json:"offset"`
	Limit       int32  `json:"limit"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotifications,
		arg.RecipientID,
		arg.Channel,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.IdempotencyKey,
			&i.Type,
			&i.Channel,
			&i.RecipientID,
			&i.RecipientAddress,
			&i.TemplateID,
			&i.Payload,
			&i.Priority,
			&i.Status,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationStatus = `-- name: UpdateNotificationStatus :one
UPDATE notifications
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, idempotency_key, type, channel, recipient_id, recipient_address, template_id, payload, priority, status, scheduled_at, created_at, updated_at
`

type UpdateNotificationStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, updateNotificationStatus, arg.ID, arg.Status)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Type,
		&i.Channel,
		&i.RecipientID,
		&i.RecipientAddress,
		&i.TemplateID,
		&i.Payload,
		&i.Priority,
		&i.Status,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
