// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: preference.sql

package db

import (
	"context"
	"database/sql"
)

const deletePreference = `-- name: DeletePreference :exec
DELETE FROM preferences
WHERE user_id = $1 AND channel = $2
`

type DeletePreferenceParams struct {
	UserID  string `json:"user_id"`
	Channel string `json:"channel"`
}

func (q *Queries) DeletePreference(ctx context.Context, arg DeletePreferenceParams) error {
	_, err := q.db.ExecContext(ctx, deletePreference, arg.UserID, arg.Channel)
	return err
}

const getPreference = `-- name: GetPreference :one
SELECT id, user_id, channel, enabled, quiet_hours_start, quiet_hours_end, frequency_cap, frequency_window_minutes, timezone, created_at, updated_at FROM preferences
WHERE user_id = $1 AND channel = $2
`

type GetPreferenceParams struct {
	UserID  string `json:"user_id"`
	Channel string `json:"channel"`
}

func (q *Queries) GetPreference(ctx context.Context, arg GetPreferenceParams) (Preference, error) {
	row := q.db.QueryRowContext(ctx, getPreference, arg.UserID, arg.Channel)
	var i Preference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Channel,
		&i.Enabled,
		&i.QuietHoursStart,
		&i.QuietHoursEnd,
		&i.FrequencyCap,
		&i.FrequencyWindowMinutes,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPreferencesByUser = `-- name: ListPreferencesByUser :many
SELECT id, user_id, channel, enabled, quiet_hours_start, quiet_hours_end, frequency_cap, frequency_window_minutes, timezone, created_at, updated_at FROM preferences
WHERE user_id = $1
ORDER BY channel ASC
`

func (q *Queries) ListPreferencesByUser(ctx context.Context, userID string) ([]Preference, error) {
	rows, err := q.db.QueryContext(ctx, listPreferencesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Preference{}
	for rows.Next() {
		var i Preference
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Channel,
			&i.Enabled,
			&i.QuietHoursStart,
			&i.QuietHoursEnd,
			&i.FrequencyCap,
			&i.FrequencyWindowMinutes,
			&i.Timezone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPreference = `-- name: UpsertPreference :one
INSERT INTO preferences (
    user_id,
    channel,
    enabled,
    quiet_hours_start,
    quiet_hours_end,
    frequency_cap,
    frequency_window_minutes,
    timezone
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (user_id, channel) DO UPDATE SET
    enabled                  = EXCLUDED.enabled,
    quiet_hours_start        = EXCLUDED.quiet_hours_start,
    quiet_hours_end          = EXCLUDED.quiet_hours_end,
    frequency_cap            = EXCLUDED.frequency_cap,
    frequency_window_minutes = EXCLUDED.frequency_window_minutes,
    timezone                 = EXCLUDED.timezone,
    updated_at               = NOW()
RETURNING id, user_id, channel, enabled, quiet_hours_start, quiet_hours_end, frequency_cap, frequency_window_minutes, timezone, created_at, updated_at
`

type UpsertPreferenceParams struct {
	UserID                 string         `json:"user_id"`
	Channel                string         `json:"channel"`
	Enabled                bool           `json:"enabled"`
	QuietHoursStart        sql.NullTime   `json:"quiet_hours_start"`
	QuietHoursEnd          sql.NullTime   `json:"quiet_hours_end"`
	FrequencyCap           sql.NullInt32  `json:"frequency_cap"`
	FrequencyWindowMinutes sql.NullInt32  `json:"frequency_window_minutes"`
	Timezone               sql.NullString `json:"timezone"`
}

func (q *Queries) UpsertPreference(ctx context.Context, arg UpsertPreferenceParams) (Preference, error) {
	row := q.db.QueryRowContext(ctx, upsertPreference,
		arg.UserID,
		arg.Channel,
		arg.Enabled,
		arg.QuietHoursStart,
		arg.QuietHoursEnd,
		arg.FrequencyCap,
		arg.FrequencyWindowMinutes,
		arg.Timezone,
	)
	var i Preference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Channel,
		&i.Enabled,
		&i.QuietHoursStart,
		&i.QuietHoursEnd,
		&i.FrequencyCap,
		&i.FrequencyWindowMinutes,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
