// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: template.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countTemplates = `-- name: CountTemplates :one
SELECT COUNT(*) FROM templates
WHERE
    tenant_id = $1 AND
    ($2::text = '' OR channel = $2)
`

type CountTemplatesParams struct {
	TenantID uuid.NullUUID `json:"tenant_id"`
	Channel  string        `json:"channel"`
}

func (q *Queries) CountTemplates(ctx context.Context, arg CountTemplatesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTemplates, arg.TenantID, arg.Channel)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTemplate = `-- name: DeleteTemplate :one
UPDATE templates
SET is_active = false, updated_at = NOW()
WHERE id = $1 AND tenant_id = $2
RETURNING id, name, channel, subject_template, body_template, metadata, version, is_active, created_at, updated_at, tenant_id
`

type DeleteTemplateParams struct {
	ID       uuid.UUID     `json:"id"`
	TenantID uuid.NullUUID `json:"tenant_id"`
}

func (q *Queries) DeleteTemplate(ctx context.Context, arg DeleteTemplateParams) (Template, error) {
	row := q.db.QueryRowContext(ctx, deleteTemplate, arg.ID, arg.TenantID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Channel,
		&i.SubjectTemplate,
		&i.BodyTemplate,
		&i.Metadata,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const getTemplateByID = `-- name: GetTemplateByID :one
SELECT id, name, channel, subject_template, body_template, metadata, version, is_active, created_at, updated_at, tenant_id FROM templates
WHERE id = $1 AND tenant_id = $2
`

type GetTemplateByIDParams struct {
	ID       uuid.UUID     `json:"id"`
	TenantID uuid.NullUUID `json:"tenant_id"`
}

func (q *Queries) GetTemplateByID(ctx context.Context, arg GetTemplateByIDParams) (Template, error) {
	row := q.db.QueryRowContext(ctx, getTemplateByID, arg.ID, arg.TenantID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Channel,
		&i.SubjectTemplate,
		&i.BodyTemplate,
		&i.Metadata,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const getTemplateByName = `-- name: GetTemplateByName :one
SELECT id, name, channel, subject_template, body_template, metadata, version, is_active, created_at, updated_at, tenant_id FROM templates
WHERE name = $1 AND tenant_id = $2 AND is_active = true
`

type GetTemplateByNameParams struct {
	Name     string        `json:"name"`
	TenantID uuid.NullUUID `json:"tenant_id"`
}

func (q *Queries) GetTemplateByName(ctx context.Context, arg GetTemplateByNameParams) (Template, error) {
	row := q.db.QueryRowContext(ctx, getTemplateByName, arg.Name, arg.TenantID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Channel,
		&i.SubjectTemplate,
		&i.BodyTemplate,
		&i.Metadata,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const insertTemplate = `-- name: InsertTemplate :one
INSERT INTO templates (
    tenant_id,
    name,
    channel,
    subject_template,
    body_template,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, name, channel, subject_template, body_template, metadata, version, is_active, created_at, updated_at, tenant_id
`

type InsertTemplateParams struct {
	TenantID        uuid.NullUUID         `json:"tenant_id"`
	Name            string                `json:"name"`
	Channel         string                `json:"channel"`
	SubjectTemplate sql.NullString        `json:"subject_template"`
	BodyTemplate    string                `json:"body_template"`
	Metadata        pqtype.NullRawMessage `json:"metadata"`
}

func (q *Queries) InsertTemplate(ctx context.Context, arg InsertTemplateParams) (Template, error) {
	row := q.db.QueryRowContext(ctx, insertTemplate,
		arg.TenantID,
		arg.Name,
		arg.Channel,
		arg.SubjectTemplate,
		arg.BodyTemplate,
		arg.Metadata,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Channel,
		&i.SubjectTemplate,
		&i.BodyTemplate,
		&i.Metadata,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, name, channel, subject_template, body_template, metadata, version, is_active, created_at, updated_at, tenant_id FROM templates
WHERE
    tenant_id = $1 AND
    ($2::text = '' OR channel = $2)
ORDER BY name ASC
LIMIT $4 OFFSET $3
`

type ListTemplatesParams struct {
	TenantID uuid.NullUUID `json:"tenant_id"`
	Channel  string        `json:"channel"`
	Offset   int32         `json:"offset"`
	Limit    int32         `json:"limit"`
}

func (q *Queries) ListTemplates(ctx context.Context, arg ListTemplatesParams) ([]Template, error) {
	rows, err := q.db.QueryContext(ctx, listTemplates,
		arg.TenantID,
		arg.Channel,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Channel,
			&i.SubjectTemplate,
			&i.BodyTemplate,
			&i.Metadata,
			&i.Version,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates
SET
    subject_template = COALESCE($2, subject_template),
    body_template    = COALESCE($3, body_template),
    metadata         = COALESCE($4, metadata),
    is_active        = COALESCE($5, is_active),
    version          = version + 1,
    updated_at       = NOW()
WHERE id = $1 AND tenant_id = $6
RETURNING id, name, channel, subject_template, body_template, metadata, version, is_active, created_at, updated_at, tenant_id
`

type UpdateTemplateParams struct {
	ID              uuid.UUID             `json:"id"`
	SubjectTemplate sql.NullString        `json:"subject_template"`
	BodyTemplate    string                `json:"body_template"`
	Metadata        pqtype.NullRawMessage `json:"metadata"`
	IsActive        bool                  `json:"is_active"`
	TenantID        uuid.NullUUID         `json:"tenant_id"`
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.db.QueryRowContext(ctx, updateTemplate,
		arg.ID,
		arg.SubjectTemplate,
		arg.BodyTemplate,
		arg.Metadata,
		arg.IsActive,
		arg.TenantID,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Channel,
		&i.SubjectTemplate,
		&i.BodyTemplate,
		&i.Metadata,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}
