// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: template.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countTemplates = `-- name: CountTemplates :one
SELECT COUNT(*) FROM templates
WHERE ($1::text = '' OR channel = $1)
`

func (q *Queries) CountTemplates(ctx context.Context, channel string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTemplates, channel)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTemplate = `-- name: DeleteTemplate :one
UPDATE templates
SET is_active = false, updated_at = NOW()
WHERE id = $1
RETURNING id, name, channel, subject_template, body_template, metadata, version, is_active, created_at, updated_at
`

func (q *Queries) DeleteTemplate(ctx context.Context, id uuid.UUID) (Template, error) {
	row := q.db.QueryRowContext(ctx, deleteTemplate, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Channel,
		&i.SubjectTemplate,
		&i.BodyTemplate,
		&i.Metadata,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateByID = `-- name: GetTemplateByID :one
SELECT id, name, channel, subject_template, body_template, metadata, version, is_active, created_at, updated_at FROM templates
WHERE id = $1
`

func (q *Queries) GetTemplateByID(ctx context.Context, id uuid.UUID) (Template, error) {
	row := q.db.QueryRowContext(ctx, getTemplateByID, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Channel,
		&i.SubjectTemplate,
		&i.BodyTemplate,
		&i.Metadata,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateByName = `-- name: GetTemplateByName :one
SELECT id, name, channel, subject_template, body_template, metadata, version, is_active, created_at, updated_at FROM templates
WHERE name = $1 AND is_active = true
`

func (q *Queries) GetTemplateByName(ctx context.Context, name string) (Template, error) {
	row := q.db.QueryRowContext(ctx, getTemplateByName, name)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Channel,
		&i.SubjectTemplate,
		&i.BodyTemplate,
		&i.Metadata,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTemplate = `-- name: InsertTemplate :one
INSERT INTO templates (
    name,
    channel,
    subject_template,
    body_template,
    metadata
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, name, channel, subject_template, body_template, metadata, version, is_active, created_at, updated_at
`

type InsertTemplateParams struct {
	Name            string                `json:"name"`
	Channel         string                `json:"channel"`
	SubjectTemplate sql.NullString        `json:"subject_template"`
	BodyTemplate    string                `json:"body_template"`
	Metadata        pqtype.NullRawMessage `json:"metadata"`
}

func (q *Queries) InsertTemplate(ctx context.Context, arg InsertTemplateParams) (Template, error) {
	row := q.db.QueryRowContext(ctx, insertTemplate,
		arg.Name,
		arg.Channel,
		arg.SubjectTemplate,
		arg.BodyTemplate,
		arg.Metadata,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Channel,
		&i.SubjectTemplate,
		&i.BodyTemplate,
		&i.Metadata,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, name, channel, subject_template, body_template, metadata, version, is_active, created_at, updated_at FROM templates
WHERE ($1::text = '' OR channel = $1)
ORDER BY name ASC
LIMIT $3 OFFSET $2
`

type ListTemplatesParams struct {
	Channel string `json:"channel"`
	Offset  int32  `json:"offset"`
	Limit   int32  `json:"limit"`
}

func (q *Queries) ListTemplates(ctx context.Context, arg ListTemplatesParams) ([]Template, error) {
	rows, err := q.db.QueryContext(ctx, listTemplates, arg.Channel, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Channel,
			&i.SubjectTemplate,
			&i.BodyTemplate,
			&i.Metadata,
			&i.Version,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates
SET
    subject_template = COALESCE($2, subject_template),
    body_template    = COALESCE($3, body_template),
    metadata         = COALESCE($4, metadata),
    is_active        = COALESCE($5, is_active),
    version          = version + 1,
    updated_at       = NOW()
WHERE id = $1
RETURNING id, name, channel, subject_template, body_template, metadata, version, is_active, created_at, updated_at
`

type UpdateTemplateParams struct {
	ID              uuid.UUID             `json:"id"`
	SubjectTemplate sql.NullString        `json:"subject_template"`
	BodyTemplate    string                `json:"body_template"`
	Metadata        pqtype.NullRawMessage `json:"metadata"`
	IsActive        bool                  `json:"is_active"`
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.db.QueryRowContext(ctx, updateTemplate,
		arg.ID,
		arg.SubjectTemplate,
		arg.BodyTemplate,
		arg.Metadata,
		arg.IsActive,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Channel,
		&i.SubjectTemplate,
		&i.BodyTemplate,
		&i.Metadata,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
