// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tenant.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, is_active, created_at, updated_at FROM tenants
WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByName = `-- name: GetTenantByName :one
SELECT id, name, is_active, created_at, updated_at FROM tenants
WHERE name = $1
`

func (q *Queries) GetTenantByName(ctx context.Context, name string) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantByName, name)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTenant = `-- name: InsertTenant :one
INSERT INTO tenants (name)
VALUES ($1)
RETURNING id, name, is_active, created_at, updated_at
`

func (q *Queries) InsertTenant(ctx context.Context, name string) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, insertTenant, name)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
