// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: webhook.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const deleteWebhookEndpoint = `-- name: DeleteWebhookEndpoint :exec
DELETE FROM webhook_endpoints
WHERE id = $1 AND tenant_id = $2
`

type DeleteWebhookEndpointParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteWebhookEndpoint(ctx context.Context, arg DeleteWebhookEndpointParams) error {
	_, err := q.db.ExecContext(ctx, deleteWebhookEndpoint, arg.ID, arg.TenantID)
	return err
}

const getWebhookEndpoint = `-- name: GetWebhookEndpoint :one
SELECT id, tenant_id, url, secret, events, is_active, created_at, updated_at FROM webhook_endpoints
WHERE id = $1 AND tenant_id = $2
`

type GetWebhookEndpointParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetWebhookEndpoint(ctx context.Context, arg GetWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRowContext(ctx, getWebhookEndpoint, arg.ID, arg.TenantID)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWebhookDelivery = `-- name: InsertWebhookDelivery :one
INSERT INTO webhook_deliveries (endpoint_id, notification_id, event, payload, status, attempt, next_retry_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, endpoint_id, notification_id, event, payload, status, attempt, next_retry_at, last_error, response_status, created_at, updated_at
`

type InsertWebhookDeliveryParams struct {
	EndpointID     uuid.UUID       `json:"endpoint_id"`
	NotificationID uuid.NullUUID   `json:"notification_id"`
	Event          string          `json:"event"`
	Payload        json.RawMessage `json:"payload"`
	Status         string          `json:"status"`
	Attempt        int32           `json:"attempt"`
	NextRetryAt    sql.NullTime    `json:"next_retry_at"`
}

func (q *Queries) InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRowContext(ctx, insertWebhookDelivery,
		arg.EndpointID,
		arg.NotificationID,
		arg.Event,
		arg.Payload,
		arg.Status,
		arg.Attempt,
		arg.NextRetryAt,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.NotificationID,
		&i.Event,
		&i.Payload,
		&i.Status,
		&i.Attempt,
		&i.NextRetryAt,
		&i.LastError,
		&i.ResponseStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWebhookEndpoint = `-- name: InsertWebhookEndpoint :one
INSERT INTO webhook_endpoints (tenant_id, url, secret, events, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, url, secret, events, is_active, created_at, updated_at
`

type InsertWebhookEndpointParams struct {
	TenantID uuid.UUID       `json:"tenant_id"`
	Url      string          `json:"url"`
	Secret   string          `json:"secret"`
	Events   json.RawMessage `json:"events"`
	IsActive bool            `json:"is_active"`
}

func (q *Queries) InsertWebhookEndpoint(ctx context.Context, arg InsertWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRowContext(ctx, insertWebhookEndpoint,
		arg.TenantID,
		arg.Url,
		arg.Secret,
		arg.Events,
		arg.IsActive,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveWebhookEndpointsForEvent = `-- name: ListActiveWebhookEndpointsForEvent :many
SELECT id, tenant_id, url, secret, events, is_active, created_at, updated_at FROM webhook_endpoints
WHERE tenant_id = $1
  AND is_active = TRUE
  AND events @> jsonb_build_array($2::text)
`

type ListActiveWebhookEndpointsForEventParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  string    `json:"column_2"`
}

func (q *Queries) ListActiveWebhookEndpointsForEvent(ctx context.Context, arg ListActiveWebhookEndpointsForEventParams) ([]WebhookEndpoint, error) {
	rows, err := q.db.QueryContext(ctx, listActiveWebhookEndpointsForEvent, arg.TenantID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEndpoint{}
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEndpoints = `-- name: ListWebhookEndpoints :many
SELECT id, tenant_id, url, secret, events, is_active, created_at, updated_at FROM webhook_endpoints
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWebhookEndpoints(ctx context.Context, tenantID uuid.UUID) ([]WebhookEndpoint, error) {
	rows, err := q.db.QueryContext(ctx, listWebhookEndpoints, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEndpoint{}
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhookDelivery = `-- name: UpdateWebhookDelivery :one
UPDATE webhook_deliveries
SET status = $2, attempt = $3, next_retry_at = $4, last_error = $5, response_status = $6, updated_at = now()
WHERE id = $1
RETURNING id, endpoint_id, notification_id, event, payload, status, attempt, next_retry_at, last_error, response_status, created_at, updated_at
`

type UpdateWebhookDeliveryParams struct {
	ID             uuid.UUID      `json:"id"`
	Status         string         `json:"status"`
	Attempt        int32          `json:"attempt"`
	NextRetryAt    sql.NullTime   `json:"next_retry_at"`
	LastError      sql.NullString `json:"last_error"`
	ResponseStatus sql.NullInt32  `json:"response_status"`
}

func (q *Queries) UpdateWebhookDelivery(ctx context.Context, arg UpdateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRowContext(ctx, updateWebhookDelivery,
		arg.ID,
		arg.Status,
		arg.Attempt,
		arg.NextRetryAt,
		arg.LastError,
		arg.ResponseStatus,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.NotificationID,
		&i.Event,
		&i.Payload,
		&i.Status,
		&i.Attempt,
		&i.NextRetryAt,
		&i.LastError,
		&i.ResponseStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWebhookEndpoint = `-- name: UpdateWebhookEndpoint :one
UPDATE webhook_endpoints
SET url = $3, events = $4, is_active = $5, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, url, secret, events, is_active, created_at, updated_at
`

type UpdateWebhookEndpointParams struct {
	ID       uuid.UUID       `json:"id"`
	TenantID uuid.UUID       `json:"tenant_id"`
	Url      string          `json:"url"`
	Events   json.RawMessage `json:"events"`
	IsActive bool            `json:"is_active"`
}

func (q *Queries) UpdateWebhookEndpoint(ctx context.Context, arg UpdateWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRowContext(ctx, updateWebhookEndpoint,
		arg.ID,
		arg.TenantID,
		arg.Url,
		arg.Events,
		arg.IsActive,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
